#!/usr/bin/env python3
"""docs/status.md: what works today, generated from the extensions'
manifests, facades, tests, demos and live pages (research3's
"release-readiness feature matrix", this repo's column).
    scripts/status.py          # write docs/status.md
    scripts/status.py --check  # fail if docs/status.md is out of date
"""
import pathlib
import re
import sys

root = pathlib.Path(__file__).resolve().parent.parent
RELEASE_1 = ["hello", "clock", "sqlite"]
MEDIA = ["canvas", "scene", "audio"]
# the extensions built after release 1, by the group they came in
LATER = {"web": "web (saga 9)", "image": "photo lab (saga 10)", "linalg": "photo lab (saga 10)",
         "http": "fetch (saga 11)", "digest": "fetch (saga 11)"}
LIVE = "https://softwarewrighter.github.io/X_eTaL-extensions"

# The extensions column of the ecosystem dashboard: hand-kept, one line
# per capability, what this repo does with it today.
CAPABILITIES = [
    ("native calls from X_eTaL", "through the bridge: `xetal-x` and the `ext:` channel (ask E1 for core support, X_eTaL Saga 23)"),
    ("typed facades (`.xtl`)", "yes: every extension's `lib/NAME.xtl`, types pinned by reg-rs"),
    ("macro helpers (`.xtlm`)", "yes: the binding macro `lib/Ffi.xtlm` writes every facade function from a signature line (ask E2 landed; E7 worked around)"),
    ("native ABI", "V1: scalars, text, dense arrays of rank 0 to 9; no handles yet"),
    ("browser", "no: extensions are native; the site shows recordings of the demos (the WebAssembly pages were retired, 2026-10-03)"),
    ("demo recordings", "`just videos`: vhs for terminal demos, headless frames for window demos; nothing on screen"),
    ("native windows", "yes: `xetal-x` serves windows on the main thread for extensions linked into it (canvas)"),
    ("command line", "every extension, with `xetal-x`"),
    ("tests", "Rust tests per extension and crate; reg-rs goldens of every facade, demo and error"),
]


def facade(d):
    libs = sorted((d / "lib").glob("*.xtl"))
    if not libs:
        return "--"
    m = re.search(r'Import:\s*"([^"]+)"\s*u_se<\s*"([^"]+)"', libs[0].read_text())
    return f"`{m.group(2)}` (`{m.group(1)}`)" if m else f"`{libs[0].stem}`"


def native(d):
    lst = d / "tests" / f"{d.name}-list.out"
    if not lst.exists():
        return 0
    return sum(1 for line in lst.read_text().splitlines() if line.startswith("  "))


def rust_tests(d):
    files = list((d / "rust").rglob("*.rs"))
    return sum(f.read_text().count("#[test]") for f in files)


def host(d):
    return "host = true" in (d / "extension.toml").read_text()


def row(d):
    name = d.name
    demos = sorted(p.stem for p in (d / "demos").glob("*.xtl") if p.stem[0].islower())
    videos = sorted(p.stem for p in (d / "videos").glob("*.webm"))
    return "| {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
        f"[{name}](../extensions/{name}/docs/README.md)",
        "release 1" if name in RELEASE_1 else "media (saga 5)" if name in MEDIA else LATER.get(name, "roadmap"),
        facade(d),
        native(d),
        rust_tests(d),
        len(list((d / "tests").glob("*.rgt"))),
        ", ".join(demos) if demos else "--",
        ", ".join(f"[{v}](../extensions/{name}/videos/{v}.webm)" for v in videos) or "--",
        "native window (xetal-x)" if host(d) else "command line",
    )


def page():
    exts = sorted(p.parent for p in root.glob("extensions/*/extension.toml"))
    planned = ["web", "image", "linalg", "http", "digest", "regex"]
    lines = [
        "# What works today",
        "",
        "Generated by `scripts/status.py` from the extensions' manifests,",
        "facades, tests, demos and live pages; the gate fails when it is out",
        "of date. Release 1 is hello, clock and sqlite (docs/plan.md).",
        "",
        "## Extensions",
        "",
        "| Extension | Built in | Facade (alias) | Native functions | Rust tests | reg-rs tests | Demos | Recordings | Runs |",
        "| --------- | ------- | -------------- | ---------------- | ---------- | ------------ | ----- | ---------- | ---- |",
        *[row(d) for d in exts],
        "",
        "Roadmap, not started: " + (", ".join(p for p in planned if not (root / "extensions" / p).exists()) or "none") + ".",
        "",
        "## Capabilities",
        "",
        "This repository's column of the X_eTaL ecosystem's dashboard.",
        "",
        "| Capability | Today |",
        "| ---------- | ----- |",
        *[f"| {c} | {t} |" for c, t in CAPABILITIES],
        "",
    ]
    return "\n".join(lines)


out = root / "docs" / "status.md"
text = page()
if "--check" in sys.argv:
    if not out.exists() or out.read_text() != text:
        sys.exit("docs/status.md is out of date: run scripts/status.py")
    print("status: ok")
else:
    out.write_text(text)
    print("docs/status.md written")
